
data_paths:
  eeg_data_dir: "/nfs/turbo/umms-mattislab/Chandni/Data/Natus/FCD/Xiaogang_Chemogenetics/"
  photometry_data_dir: "./FiberPhotometryData"
  output_dir: "./output"
  seizure_onsets_file: "./config/seizure_onsets.json"

preprocessing:
  eeg_sampling_freq: 4096.0
  notch_frequency: 60.0
  notch_quality: 30.0
  bandpass_low: 1.0
  bandpass_high: 70.0
  interpolation_threshold: 3.0

  savgol_window: 301
  savgol_polyorder: 4
  gaussian_sigma: 75.0
  lowpass_cutoff: 10.0
  
  exp_fit_max_iterations: 1000
  exp_fit_bounds_multiplier: 2.0

detection:
  fs: 4096.0
  tmul: 4.5
  absthresh: 0.4
  sur_time: 1000.0
  close_to_edge: 0.05
  too_high_abs: 1000000000.0
  spkdur_min: 20.0
  spkdur_max: 200.0
  baseline_end_time: 480.0
  baseline_start_time: 120.0
  use_adaptive_detection: false
  multi_channel_requirements: false

visualization:
  default_renderer: "browser"
  max_plot_points: 10000
  downsample_factor: 10
  figure_width: 1200
  figure_height: 800
  line_width: 1.0
  spike_marker_size: 10
  spike_marker_color: "red"

log_level: "INFO"
log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
default_channel: '4 RP'
processing_strategy: "meiling1"  # "meiling" or "chandni"